on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 0 * * *'

name: Update bot API

jobs:
  scrap-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'

      - name: Install Composer dependencies
        uses: php-actions/composer@v6

      - name: Scrap API docs
        run: composer run scrap

      - name: Check if updated
        id: check_api
        run: |
          if git diff --quiet --exit-code api.json; then
            echo "api_changed=false" >> $GITHUB_OUTPUT
          else
            echo "api_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run generate command
        if: steps.check_api.outputs.api_changed == 'true'
        run: |
          composer run generate
          vendor/bin/pint
          vendor/bin/rector

      - name: Configure Git
        if: steps.check_api.outputs.api_changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        if: steps.check_api.outputs.api_changed == 'true'
        run: |
          git checkout -b auto/api-update
          git add .
          git commit -m "Update bot API"
          git push origin auto/api-update

      - name: Create Pull Request
        if: steps.check_api.outputs.api_changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          branch: auto/api-update
          title: "Update Telegram bot API"
          body: "This pull request was automatically generated by the GitHub Actions workflow."
          base: 4.x
